more fixes for init and path conflicts

diff --git a/smnnepo.init b/smnnepo.init
--- a/smnnepo.init
+++ b/smnnepo.init
@@ -3,7 +3,6 @@
 # chkconfig:   345 99 01
 # description: Starts and stops the OpenNMS SMNnepO distributed client
 # processname: java
-# pidfile:     /var/run/smnnepo.pid
 #
 ### BEGIN INIT INFO
 # Provides:          smnnepo
@@ -20,7 +19,6 @@
 NAME="smnnepo"
 DESC="SMNnepO Distributed Client"
 PATH=/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin
-PIDFILE="/var/run/$NAME.pid"
 SMNNEPO_HOME="@INSTPREFIX@"
 OPENNMS="http://localhost:8980/"
 LOCATION="Default"
@@ -35,31 +33,14 @@ elif [ -f "/etc/sysconfig/$NAME" ]; then
         . $CONFFILE
 fi
 
-pid_running() {
-	if [ -f "$PIDFILE" ]; then
-		# Pull the PID out of the pidfile
-		POLLER_PID=`cat $PIDFILE`
-		if [ ! -z $POLLER_PID ]; then
-			# Check to see if the process is still alive
-			ps -p $POLLER_PID >/dev/null 2>&1
-			# If it is dead, then unset POLLER_PID
-			if [ $? -gt 0 ]; then
-				rm -f "$PIDFILE"
-				unset POLLER_PID
-				return
-			fi
-
-			return 
-		fi
-	fi
-	return
+is_running() {
+	"$SMNNEPO_HOME"/bin/status >/dev/null
 }
 
 case "$1" in
 
 	start)
-		pid_running
-		if [ ! -z $POLLER_PID ]; then
+		if is_running; then
 			echo "$DESC is running."
 			exit 0
 		fi
@@ -75,45 +56,29 @@ case "$1" in
 			exit 0
 		fi
 
-		if [ -x /sbin/start-stop-daemon ]; then
-			start-stop-daemon --start --background --quiet --oknodo --pidfile $PIDFILE --make-pidfile $CHUID --startas $SMNNEPO_HOME/bin/karaf -- server >/dev/null
-			if $?; then
-				sleep 5
-				echo "running script"
-			fi
+		"$SMNNEPO_HOME"/bin/start >/dev/null
+		RETVAL="$?"
+		if [ $RETVAL -eq 0 ]; then
+			sleep 5
+			echo "running script"
 		else
-			$SUDO_PREFIX $SMNNEPO_HOME/bin/karaf server &
-			RETVAL="$?"
-			echo "$!" > "$PIDFILE"
-			if $RETVAL; then
-				echo "OK"
-				echo "running script"
-				exit 0
-			else
-				echo "FAILED"
-				exit $RETVAL
-			fi
+			exit $RETVAL
 		fi
-		#echo "."
 		;;
 
 	stop)
-		echo -n "Stopping $DESC: "
-		if [ -x /sbin/start-stop-daemon ]; then
-			start-stop-daemon --stop --quiet --retry 15 --pidfile $PIDFILE > /dev/null
-			#echo "."
-		else
-			pid_running
-			if [ ! -z $POLLER_PID ]; then
-				kill `cat $PIDFILE`
-				rm -f "$PIDFILE" 2>&1
-			else 
-				echo "FAILED: $DESC is not running."
+		if is_running; then
+			"$SMNNEPO_HOME"/bin/stop >/dev/null
+			RETVAL="$?"
+			if [ $RETVAL -eq 0 ]; then
+				exit 0
+			else
+				echo "FAILED"
 				exit 1
 			fi
-
-			echo "OK"
-			exit 0
+		else
+			echo "FAILED: $DESC is not running."
+			exit 1
 		fi
 		;;
 
@@ -125,13 +90,13 @@ case "$1" in
 		;;
 
 	try-restart)
-		pid_running
-		if [ ! -z $POLLER_PID ]; then
+		if is_running; then
+			echo "$DESC is not running."
+			exit 0
+		else
 			$0 restart
 			exit $?
 		fi
-		echo "$DESC not running."
-		exit 0
 		;;
 
 
@@ -141,8 +106,9 @@ case "$1" in
 		;;
 
 	status)
-		pid_running
-		if [ ! -z $POLLER_PID ]; then
+		"$SMNNEPO_HOME"/bin/status >/dev/null
+		RETVAL="$?"
+		if [ $RETVAL -eq 0 ]; then
 			echo "$DESC is running."
 			exit 0
 		else
